name: Build and Test

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [prod]

jobs:
  build_test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repo Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
      
      - name: Install Node Modules
        run: npm install

      # This is just specific to Netlify hosted websites, would be different depending on what platform you host on
      - name: Deploy to Netlify
        id: build_site
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: './dist'
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

      - name: Test URL
        run: echo ${{steps.build_site.outputs.deploy_url}}