name: Build and Publish on Azure as a Static Web App

on:
  push:
    branches: [prod]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repo Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Add Issues from Comments
        uses: "alstr/todo-to-issue-action@v4"
        with:
          AUTO_ASSIGN: true
          CLOSE_ISSUES: true

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BRAVE_CLIFF_0F44EC203 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          api_location: "api"
          output_location: "dist"
