name: Build and Publish on Netlify

on:
  push:
    branches: [prod]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repo Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Add Issues from Comments
        uses: "alstr/todo-to-issue-action@v4"
        with:
          AUTO_ASSIGN: true
          CLOSE_ISSUES: true

      - name: Install Node Packages
        run: npm install

      - name: Deploy to Netlify
        id: build_site
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: ./_actions/netlify_deploy.sh --p true