name: Build and Test

on:
  pull_request:
    branches: [prod]
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Deploy to Netlify
        id: build_site
        env:
          TOKEN: ${{ secrets.TOKEN }}
          SITE_ID: ${{ secrets.SITE_ID }}
        run: ./github/actions/netlify_deploy.sh

      - uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'The build works! You can view the deploy preview at ${{steps.build_site.outputs.NETLIFY_URL}}'
            })
